[package]
name = "record_keeper"
version = "0.1.0"
authors = ["William Gollinger <wgolling@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
chrono = { version = "0.4", features = ["serde"] }